{% set name = "terratorch" %}
{% set version = "1.2.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/terratorch-{{ version }}.tar.gz
  sha256: 7e3c4a82ffa54c7317d0fd964103acbedf4b4ffd627c7ddf6b1d63c048cd70f6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - terratorch = terratorch.__main__:main
  #skip: true  # [win]

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - pyarrow
    - rich
    - tacoreader ==0.5.6
    - diffusers
    - numpy >=2.2
    - scikit-image
    - scikit-learn >=1.3.2
    - tqdm
    - python >={{ python_min }}
    - pytorch >2.0
    - torchvision
    - rioxarray
    - albumentations
    - albucore
    - rasterio
    - torchmetrics
    - geopandas
    - lightly ==1.5.22
    - jsonargparse >=4.40.0
    - h5py
    - hdf5plugin
    - numba
    - mlflow
    - lightning >=2.6.0
    - segmentation-models-pytorch
    - jsonargparse
    - torchgeo
    - einops
    - timm >=1.0.15
    - pycocotools
    - huggingface_hub
    - tifffile
    - python-box
    - wandb >=0.18.0
    - termcolor
    - numba
    - hdf5plugin
    - h5netcdf
    - pytest-sugar
    - tensorboard
    - wandb
test:
  imports:
    - terratorch
    - terratorch.models
    - terratorch.models.backbones
    - terratorch.datamodules
    - terratorch.datasets
    - terratorch.samplers
  commands:
    - pip check
    - terratorch --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/terrastackai/terratorch
  summary: TerraTorch - A model training toolkit for geospatial tasks
  doc_url: https://terrastackai.github.io/terratorch/
  dev_url: https://github.com/terrastackai/terratorch
  license: Apache-2.0
  license_file: LICENSE
  description: |
    The purpose of this package is to build a flexible fine-tuning framework for Geospatial Foundation Models (GFMs)
    based on TorchGeo and Lightning which can be employed at different abstraction levels. It supports models from the Prithvi,
    TerraMind, and Granite series as well as models from TorchGeo and timm.

    This library provides

    1. Ease-of-use and all the functionality from Lightning and TorchGeo.
    2. A modular model factory that combines any backbone with different decoders for full flexibility.
    3. Ready-to-use tasks for image segmentation, pixelwise regression, classification, and more.
    4. Multiple abstraction levels and inference pipelines to power enterprise applications.

extra:
  recipe-maintainers:
    - weiji14
    - Joao-L-S-Almeida
    - romeokienzler
    - giswqs
